# -*- coding: utf-8 -*-
"""empty message

Revision ID: 0875273c0936
Revises: 759f1ba87fa5
Create Date: 2020-06-19 23:05:50.099488

"""

# revision identifiers, used by Alembic.
revision = '0875273c0936'
down_revision = '759f1ba87fa5'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_created')
        batch_op.drop_column('last_modified')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
