"""empty message

Revision ID: 36954739c63
Revises: 15f27bc43bd
Create Date: 2015-11-23 21:00:24.105026

"""

# revision identifiers, used by Alembic.
revision = '36954739c63'
down_revision = '15f27bc43bd'

from datetime import datetime

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=True))
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sqlalchemy_utils.types.password.PasswordType(max_length=128),
               existing_nullable=False,
               postgresql_using='password::bytea')
    ### end Alembic commands ###

    user = sa.Table('user',
        sa.MetaData(),
        sa.Column('created', sa.DateTime()),
        sa.Column('updated', sa.DateTime()),
    )

    op.execute(
        user.update().values({'created': datetime.now(), 'updated': datetime.now()})
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('password',
               existing_type=sqlalchemy_utils.types.password.PasswordType(max_length=128),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('updated')
        batch_op.drop_column('created')
    ### end Alembic commands ###
