"""empty message

Revision ID: 43e8118c59c5
Revises: b9c3d8d67e54
Create Date: 2020-10-09 13:50:31.811374

"""

# revision identifiers, used by Alembic.
revision = '43e8118c59c5'
down_revision = 'b9c3d8d67e54'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('commit_houston_api_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('commit_mime_whitelist_guid',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('commit_mime_whitelist_guid',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.alter_column('commit_houston_api_version',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
