# -*- coding: utf-8 -*-
"""empty message

Revision ID: 5bc2e2704741
Revises: fd469e3e5b9b
Create Date: 2020-06-16 15:07:20.880684

"""

# revision identifiers, used by Alembic.
revision = '5bc2e2704741'
down_revision = 'fd469e3e5b9b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from datetime import datetime


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'accepted_user_agreement',
                sa.Boolean(),
                nullable=False,
                server_default='FALSE',
            )
        )
        batch_op.add_column(
            sa.Column(
                'viewed',
                sa.DateTime(),
                nullable=False,
                server_default='%s' % (datetime.utcnow(),),
            )
        )
        batch_op.alter_column(
            'full_name',
            existing_type=sa.VARCHAR(length=30),
            type_=sa.String(length=120),
            existing_nullable=False,
            existing_server_default=sa.text("('')"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'full_name',
            existing_type=sa.String(length=120),
            type_=sa.VARCHAR(length=30),
            existing_nullable=False,
            existing_server_default=sa.text("('')"),
        )
        batch_op.drop_column('viewed')
        batch_op.drop_column('accepted_user_agreement')

    # ### end Alembic commands ###
