# -*- coding: utf-8 -*-
"""empty message

Revision ID: 759f1ba87fa5
Revises: ff232fed26c0
Create Date: 2020-06-16 16:21:19.860483

"""

# revision identifiers, used by Alembic.
revision = '759f1ba87fa5'
down_revision = 'ff232fed26c0'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from datetime import datetime
import app


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'accepted_user_agreement',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column('affiliation', sa.String(length=120), nullable=True)
        )
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'default_identification_catalogue', app.extensions.GUID(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column('footer_logo_asset_guid', app.extensions.GUID(), nullable=True)
        )
        batch_op.add_column(sa.Column('forum_id', sa.String(length=120), nullable=True))
        batch_op.add_column(
            sa.Column('full_name', sa.String(length=120), nullable=False, default='')
        )
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('locale', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(
            sa.Column(
                'receive_newsletter_emails',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'receive_notification_emails',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'shares_data', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                'show_email_in_profile',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'use_usa_date_format',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
        batch_op.add_column(
            sa.Column(
                'viewed',
                sa.DateTime(),
                nullable=False,
                server_default='%s' % (datetime.utcnow(),),
            )
        )
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.drop_index('ix_user_address_country')
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('address_state')
        batch_op.drop_column('last_name')
        batch_op.drop_column('address_city')
        batch_op.drop_column('first_name')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('suffix_name')
        batch_op.drop_column('title_name')
        batch_op.drop_column('phone')
        batch_op.drop_column('agreement')
        batch_op.drop_column('address_region')
        batch_op.drop_column('url')
        batch_op.drop_column('address_gps_longitude')
        batch_op.drop_column('address_gps_latitude')
        batch_op.drop_column('address_country')
        batch_op.drop_column('username')
        batch_op.drop_column('middle_name')
        batch_op.drop_column('address_line1')
        batch_op.drop_column('address_zip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('address_zip', sa.VARCHAR(length=10), nullable=True)
        )
        batch_op.add_column(
            sa.Column('address_line1', sa.VARCHAR(length=120), nullable=True)
        )
        batch_op.add_column(
            sa.Column('middle_name', sa.VARCHAR(length=30), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                'username', sa.VARCHAR(length=120), nullable=False, server_default=''
            )
        )
        batch_op.add_column(
            sa.Column('address_country', sa.VARCHAR(length=30), nullable=True)
        )
        batch_op.add_column(sa.Column('address_gps_latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('address_gps_longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(
            sa.Column('address_region', sa.VARCHAR(length=30), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                'agreement', sa.BOOLEAN(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('title_name', sa.VARCHAR(length=8), nullable=True))
        batch_op.add_column(sa.Column('suffix_name', sa.VARCHAR(length=8), nullable=True))
        batch_op.add_column(
            sa.Column('address_line2', sa.VARCHAR(length=120), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                'first_name', sa.VARCHAR(length=30), nullable=False, server_default=''
            )
        )
        batch_op.add_column(
            sa.Column('address_city', sa.VARCHAR(length=120), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                'last_name', sa.VARCHAR(length=30), nullable=False, server_default=''
            )
        )
        batch_op.add_column(
            sa.Column('address_state', sa.VARCHAR(length=30), nullable=True)
        )
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.create_index(
            'ix_user_address_country', ['address_country'], unique=False
        )
        batch_op.drop_column('website')
        batch_op.drop_column('viewed')
        batch_op.drop_column('use_usa_date_format')
        batch_op.drop_column('show_email_in_profile')
        batch_op.drop_column('shares_data')
        batch_op.drop_column('receive_notification_emails')
        batch_op.drop_column('receive_newsletter_emails')
        batch_op.drop_column('location')
        batch_op.drop_column('locale')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('last_modified')
        batch_op.drop_column('full_name')
        batch_op.drop_column('forum_id')
        batch_op.drop_column('footer_logo_asset_guid')
        batch_op.drop_column('default_identification_catalogue')
        batch_op.drop_column('date_created')
        batch_op.drop_column('affiliation')
        batch_op.drop_column('accepted_user_agreement')

    # ### end Alembic commands ###
