"""empty message

Revision ID: 79771ce5f661
Revises: 43e8118c59c5
Create Date: 2020-10-09 15:20:45.494044

"""

# revision identifiers, used by Alembic.
revision = '79771ce5f661'
down_revision = '43e8118c59c5'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('filesystem_xxhash64', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_asset_extension'), ['extension'], unique=False)
        batch_op.drop_index('ix_asset_ext')
        batch_op.drop_column('ext')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magic_signiture', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('ext', sa.VARCHAR(length=5), nullable=False))
        batch_op.create_index('ix_asset_ext', ['ext'], unique=False)
        batch_op.drop_index(batch_op.f('ix_asset_extension'))
        batch_op.drop_column('magic_signature')
        batch_op.drop_column('filesystem_xxhash64')
        batch_op.drop_column('extension')

    # ### end Alembic commands ###
