"""empty message

Revision ID: a8fb9085da79
Revises: 79771ce5f661
Create Date: 2020-10-09 16:21:33.072475

"""

# revision identifiers, used by Alembic.
revision = 'a8fb9085da79'
down_revision = '79771ce5f661'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asset_submission_guid_submission', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_asset_submission_guid_submission'), 'submission', ['submission_guid'], ['guid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_asset_submission_guid_submission'), type_='foreignkey')
        batch_op.create_foreign_key('fk_asset_submission_guid_submission', 'submission', ['submission_guid'], ['guid'])

    # ### end Alembic commands ###
