# -*- coding: utf-8 -*-
"""empty message

Revision ID: ea359477fe5b
Revises: 759f1ba87fa5
Create Date: 2020-06-18 16:28:33.372155

"""

# revision identifiers, used by Alembic.
revision = 'ea359477fe5b'
down_revision = '759f1ba87fa5'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions

from datetime import datetime


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'collaboration',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('guid', app.extensions.GUID(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('guid', name=op.f('pk_collaboration')),
    )
    op.create_table(
        'encounter',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('viewed', sa.DateTime(), nullable=False),
        sa.Column('guid', app.extensions.GUID(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('guid', name=op.f('pk_encounter')),
    )
    op.create_table(
        'organization',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('guid', app.extensions.GUID(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('guid', name=op.f('pk_organization')),
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'viewed',
                sa.DateTime(),
                nullable=False,
                server_default='%s' % (datetime.utcnow(),),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('viewed')

    op.drop_table('organization')
    op.drop_table('encounter')
    op.drop_table('collaboration')
    # ### end Alembic commands ###
