"""empty message

Revision ID: f4f2436d30f2
Revises: ea359477fe5b
Create Date: 2020-09-11 12:07:09.993050

"""

# revision identifiers, used by Alembic.
revision = 'f4f2436d30f2'
down_revision = 'ea359477fe5b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import app
import app.extensions



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('viewed', sa.DateTime(), nullable=False),
    sa.Column('guid', app.extensions.GUID(), nullable=False),
    sa.Column('submission_major_type', sa.Enum('filesystem', 'archive', 'service', 'unknown', 'error', 'reject', name='submissionmajortype'), nullable=True),
    sa.Column('commit', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('owner_guid', app.extensions.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_guid'], ['user.guid'], name=op.f('fk_submission_owner_guid_user')),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_submission')),
    sa.UniqueConstraint('commit', name=op.f('uq_submission_commit'))
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_owner_guid'), ['owner_guid'], unique=False)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('submission_guid', app.extensions.GUID(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_asset_submission_guid'), ['submission_guid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_asset_submission_guid_submission'), 'submission', ['submission_guid'], ['guid'])
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_asset_submission_guid_submission'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_asset_submission_guid'))
        batch_op.drop_column('title')
        batch_op.drop_column('submission_guid')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('meta')
        batch_op.drop_column('description')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_owner_guid'))

    op.drop_table('submission')
    # ### end Alembic commands ###
